---
dependency:
  name: galaxy
  roles:
    - jonathonball.docker
driver:
  name: docker
platforms:
  - name: instance
    image: docker.io/pycontribs/ubuntu
provisioner:
  name: ansible
verifier:
  name: ansible
